In [1]:
import numpy as np

In [4]:
pts = np.array([
    [[3, 5, 7], [5, 3, 2]],
    [[1, 3, 4], [1, 4, 6]]
])

pts2 =  np.array([
    [[1, 3, 4], [1, 4, 6]],
    [[3, 5, 7], [5, 3, 2]],
])

In [5]:
pts - pts2

array([[[ 2,  2,  3],
        [ 4, -1, -4]],

       [[-2, -2, -3],
        [-4,  1,  4]]])

In [15]:
dists = np.sum((pts - pts2)**2, axis=-1)**0.5
dists

array([[4.12310563, 5.74456265],
       [4.12310563, 5.74456265]])

In [16]:
4.12310563/5.74456265

0.7177405628955932

In [14]:
dists[:, 0]/dists[:, 1]

array([0.71774056, 0.71774056])